//! Injected randomness source.
//!
//! Key generation and every other consumer of randomness receives a
//! [`RandomSource`] rather than calling an operating-system or library RNG
//! directly, so tests can reproduce byte-exact outputs deterministically
//! (IMPLEMENTATION.md section 7.3).

use std::sync::atomic::{AtomicU64, Ordering};

/// Failure of the underlying randomness source.
#[derive(Debug, thiserror::Error)]
#[error("randomness source failed: {0}")]
pub struct RandomError(getrandom::Error);

/// A source of random bytes.
///
/// Only [`OsRandom`] is suitable for real key material. Deterministic
/// implementations exist for tests and must never back a production identity.
pub trait RandomSource {
    /// Fills `dest` completely with random bytes.
    ///
    /// # Errors
    ///
    /// Returns a [`RandomError`] when the underlying source cannot supply
    /// the requested bytes; partial fills are never exposed.
    fn fill(&self, dest: &mut [u8]) -> Result<(), RandomError>;
}

/// Production randomness backed by the operating-system CSPRNG.
#[derive(Debug, Default, Clone, Copy)]
pub struct OsRandom;

impl RandomSource for OsRandom {
    fn fill(&self, dest: &mut [u8]) -> Result<(), RandomError> {
        getrandom::fill(dest).map_err(RandomError)
    }
}

/// Deterministic, seedable byte stream for tests and tools.
///
/// **Not cryptographically secure.** The stream is a SplitMix64 generator:
/// trivially predictable from its seed by design, so fixtures can be
/// regenerated byte-for-byte. It must never back a production identity;
/// production commands must not accept it.
#[derive(Debug)]
pub struct DeterministicRandom {
    state: AtomicU64,
}

impl DeterministicRandom {
    /// Creates a stream that always produces the same bytes for `seed`.
    #[must_use]
    pub fn from_seed(seed: u64) -> Self {
        Self {
            state: AtomicU64::new(seed),
        }
    }

    /// SplitMix64 output function; wrapping arithmetic is the algorithm's
    /// definition, not an overflow hazard.
    fn next_u64(&self) -> u64 {
        let advanced = self
            .state
            .fetch_add(0x9E37_79B9_7F4A_7C15, Ordering::SeqCst)
            .wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = advanced;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }
}

impl RandomSource for DeterministicRandom {
    fn fill(&self, dest: &mut [u8]) -> Result<(), RandomError> {
        for chunk in dest.chunks_mut(8) {
            let bytes = self.next_u64().to_le_bytes();
            chunk.copy_from_slice(&bytes[..chunk.len()]);
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn os_random_fills_and_varies() {
        let mut a = [0u8; 32];
        let mut b = [0u8; 32];
        OsRandom.fill(&mut a).expect("OS randomness available");
        OsRandom.fill(&mut b).expect("OS randomness available");
        // 2^-256 false-failure probability is acceptable for a smoke test.
        assert_ne!(a, b, "two 32-byte OS random fills should differ");
    }

    #[test]
    fn deterministic_random_reproduces_exactly() {
        let mut a = [0u8; 24];
        let mut b = [0u8; 24];
        DeterministicRandom::from_seed(42)
            .fill(&mut a)
            .expect("deterministic fill cannot fail");
        DeterministicRandom::from_seed(42)
            .fill(&mut b)
            .expect("deterministic fill cannot fail");
        assert_eq!(a, b);

        let mut c = [0u8; 24];
        DeterministicRandom::from_seed(43)
            .fill(&mut c)
            .expect("deterministic fill cannot fail");
        assert_ne!(a, c, "different seeds should produce different streams");
    }

    #[test]
    fn deterministic_random_stream_advances() {
        let source = DeterministicRandom::from_seed(7);
        let mut first = [0u8; 16];
        let mut second = [0u8; 16];
        source.fill(&mut first).expect("fill");
        source.fill(&mut second).expect("fill");
        assert_ne!(first, second, "successive fills continue the stream");
    }

    #[test]
    fn deterministic_random_handles_partial_trailing_chunk() {
        // Length not divisible by 8 exercises the tail path; prefix of a
        // longer fill from the same seed must match a shorter fill exactly.
        let mut short = [0u8; 13];
        let mut long = [0u8; 16];
        DeterministicRandom::from_seed(9)
            .fill(&mut short)
            .expect("fill");
        DeterministicRandom::from_seed(9)
            .fill(&mut long)
            .expect("fill");
        assert_eq!(short[..], long[..13]);
    }
}
